export interface BusRoute {
  id: string;
  start: string;
  passBy: string;
  destination: string;
  distance: string;
}

export const anbessaRoutes: BusRoute[] = [
  { id: "1", start: "Megenagna", passBy: "Gurd Shola", destination: "Kara", distance: "7.7 Km" },
  { id: "2", start: "Kore Mekanisa", passBy: "Lideta", destination: "Addis Ketema", distance: "11.1 Km" },
  { id: "3", start: "Ayertena", passBy: "Mexico", destination: "Minilik Square", distance: "10.8 Km" },
  { id: "4", start: "Kaliti", passBy: "Kira", destination: "Merkato", distance: "19.4 Km" },
  { id: "5", start: "Kore Mekanisa", passBy: "SARBET", destination: "Minilik Square", distance: "12.7 Km" },
  { id: "6", start: "Kera", passBy: "MEXICO", destination: "Addisu Gebeya", distance: "9.9 Km" },
  { id: "7", start: "Megenagna", passBy: "Kotebe", destination: "Aleltu", distance: "49 Km" },
  { id: "8", start: "Kechene", passBy: "PIYYASA", destination: "Merkato", distance: "9.4 Km" },
  { id: "9", start: "Birass Cilinic Bole School", passBy: "Kasanchiz", destination: "Piazza", distance: "10.5 Km" },
  { id: "10", start: "Kotebe Teachers Collage", passBy: "Kebena", destination: "Piazza", distance: "12.7 Km" },
  { id: "11", start: "Kolfe", passBy: "Atkilt tera", destination: "Minilik Hospital", distance: "10 Km" },
  { id: "12", start: "Gurara", passBy: "FRENCAY/KILA", destination: "Merkato", distance: "9.9 Km" },
  { id: "13", start: "Italy Embassy", passBy: "Sinima Ethipia", destination: "Merkato", distance: "9.9 Km" },
  { id: "14", start: "PIYYSA", passBy: "STADIUM", destination: "BULBULA", distance: "12.3 Km" },
  { id: "15", start: "Megenagna", passBy: "Abuare", destination: "Merkato", distance: "10.5 Km" },
  { id: "16", start: "Kidanemihret", passBy: "Afnch Ber", destination: "Merkato", distance: "7.9 Km" },
  { id: "17", start: "kusquam", passBy: "kidste Mariam", destination: "Merkato", distance: "9.1 Km" },
  { id: "18", start: "keraniyo", passBy: "kolfe Dildy", destination: "Merkato", distance: "7.3 Km" },
  { id: "19", start: "Asko", passBy: "Pawlos", destination: "Piazza", distance: "12.3 Km" },
  { id: "20", start: "Dile Ber", passBy: "RUFAEL", destination: "Merkato", distance: "8.6 Km" },
  { id: "21", start: "Flidoro", passBy: "kolfe Dildy", destination: "Merkato", distance: "8.6 Km" },
  { id: "22", start: "Summit/codominium/", passBy: "22 mazoria", destination: "Legehar", distance: "12.3 Km" },
  { id: "23", start: "Lamberet", passBy: "Afnch Ber", destination: "Merkato", distance: "12.4 Km" },
  { id: "24", start: "Dire Sololia", passBy: "ASCO", destination: "Merkato", distance: "15.9 Km" },
  { id: "25", start: "Legehar", passBy: "Gotera", destination: "Akaki", distance: "19 Km" },
  { id: "26", start: "Merkato", passBy: "Coca Coal", destination: "Sebeta", distance: "25.5 Km" },
  { id: "27", start: "MEXICO", passBy: "SARBET", destination: "GELAN CONDI.", distance: "14.9 Km" },
  { id: "28", start: "Asko Sansuzi", passBy: "Mesalemia", destination: "Merkato", distance: "11.1 Km" },
  { id: "29", start: "Addisu Sefer", passBy: "Teklehaimanot", destination: "Merkato", distance: "12.7 Km" },
  { id: "30", start: "MIZAN AMAN", passBy: "Semen Gegeya", destination: "Merkato", distance: "25.5 Km" },
  { id: "31", start: "Legehar", passBy: "4 kilo", destination: "Shiromeda", distance: "7.4 Km" },
  { id: "32", start: "Hana Mariyame Kotebe", passBy: "22 Mazoria", destination: "Legehar", distance: "10.6 Km" },
  { id: "33", start: "Kotebe Gebiriel", passBy: "Kebena", destination: "4 Kilo", distance: "11.4 Km" },
  { id: "34", start: "Germen Square", passBy: "Kera", destination: "Merkato", distance: "9.8 Km" },
  { id: "35", start: "Lebu Musica bet", passBy: "Lafto", destination: "Merkato", distance: "15 Km" },
  { id: "36", start: "Kara Kore", passBy: "Torhailoch", destination: "Legehar", distance: "11.7 Km" },
  { id: "37", start: "Keraniyo", passBy: "Mexico", destination: "Mimilik Square", distance: "12 Km" },
  { id: "38", start: "Lebu Musica Bete", passBy: "Minilik Square", destination: "6 Kilo", distance: "11 Km" },
  { id: "39", start: "Bole School Medhanialem", passBy: "Kazanchiz", destination: "Merkato", distance: "9.6 Km" },
  { id: "40", start: "Kara Alo", passBy: "4 kilo", destination: "Merkato", distance: "17.9 Km" },
  { id: "41", start: "Eyesus Church", passBy: "4 kilo", destination: "Merkato", distance: "8.5 Km" },
  { id: "42", start: "Megenagna", passBy: "Bole", destination: "Bole Legehare", distance: "9.8 Km" },
  { id: "43", start: "Megenesha", passBy: "ASCO", destination: "Merkato", distance: "30.2 Km" },
  { id: "44", start: "Legedadi", passBy: "4 kilo", destination: "Merkato", distance: "30.4 Km" },
  { id: "45", start: "Legehar", passBy: "Piazza", destination: "Dilbere", distance: "8.6 Km" },
  { id: "46", start: "Gergi", passBy: "22 mazoria", destination: "4 Kilo", distance: "11.2 Km" },
  { id: "47", start: "Yenegew Fire School", passBy: "Mechael", destination: "Merkato", distance: "6 Km" },
  { id: "48", start: "ADDISUGEBEYA", passBy: "PIYYSA", destination: "BOLE", distance: "10.9 Km" },
  { id: "49", start: "Ayat Condominium", passBy: "C.M.C", destination: "Megenagna", distance: "8.8 Km" },
  { id: "50", start: "Ayeretena", passBy: "Torhailoch", destination: "Megenagna", distance: "12.1 Km" },
  { id: "51", start: "Betel Hosipital", passBy: "Zenbwork", destination: "Merkato", distance: "10.9 Km" },
  { id: "52", start: "Gergi", passBy: "Bole", destination: "Merkato", distance: "14.1 Km" },
  { id: "53", start: "Bole Michael", passBy: "Meskel square", destination: "Shiromeda", distance: "11.5 Km" },
  { id: "54", start: "Lafeto", passBy: "Kera", destination: "Leghar", distance: "9.5 Km" },
  { id: "55", start: "Legehar", passBy: "4 kilo", destination: "Gurara", distance: "9.5 Km" },
  { id: "56", start: "Saris Abo", passBy: "Meskel Square", destination: "Shiromeda", distance: "14.2 Km" },
  { id: "57", start: "Kara", passBy: "22 Mazoria", destination: "Leghar", distance: "14.4 Km" },
  { id: "58", start: "Alem Bank", passBy: "Torhailoch", destination: "Leghar", distance: "12 Km" },
  { id: "59", start: "Betel Hospital", passBy: "Coca Cola", destination: "Mililik Sqare", distance: "11.5 Km" },
  { id: "60", start: "Deber Zeit", passBy: "Gotera", destination: "Leghar", distance: "47.2 Km" },
  { id: "61", start: "Ayat Condominium", passBy: "22 Mazoria", destination: "Leghar Through Kasanchis", distance: "15.8 Km" },
  { id: "62", start: "Sebeta", passBy: "Torhailoch", destination: "Leghar", distance: "23.8 Km" },
  { id: "63", start: "Merkato", passBy: "Atena Tera", destination: "Mikililand/Birechko fabrica", distance: "9.1 Km" },
  { id: "64", start: "6 Kilo", passBy: "Kazanchiz", destination: "Megenagna Gorfe Aswegaj", distance: "9.5 Km" },
  { id: "65", start: "Merkato", passBy: "Coca cola", destination: "Alem Bank", distance: "11 Km" },
  { id: "66", start: "Merkato", passBy: "coca cola", destination: "Karakore", distance: "10.5 Km" },
  { id: "67", start: "Mekanisa Jemo", passBy: "mexico", destination: "Legehar", distance: "10.2 Km" },
  { id: "68", start: "Torhailoche", passBy: "Gibi Gebriel", destination: "Minlik Hospital", distance: "10.2 Km" },
  { id: "69", start: "Philpos Church", passBy: "Mesalemia", destination: "Merkato", distance: "5.9 Km" },
  { id: "70", start: "AJANBO CONDI.", passBy: "Mexico", destination: "PIYASA", distance: "11 Km" },
  { id: "71", start: "Gerji", passBy: "Bole Tenatabia", destination: "Balcha Hospital", distance: "11 Km" },
  { id: "72", start: "Hanamariam", passBy: "58 kebele", destination: "Saris Abo", distance: "3.8 Km" },
  { id: "73", start: "Legehar", passBy: "Torhailoch", destination: "Wingate School", distance: "10.2 Km" },
  { id: "74", start: "C.M.C Michael", passBy: "Tikur Anbessa", destination: "Merkato", distance: "13.3 Km" },
  { id: "75", start: "6 Kilo", passBy: "Kazanchiz", destination: "Kera", distance: "10.4 Km" },
  { id: "76", start: "Megenagna", passBy: "Zerihun bulding", destination: "Kaliti", distance: "18.4 Km" },
  { id: "77", start: "Ayertena", passBy: "Sar bet", destination: "Kera", distance: "13 Km" },
  { id: "78", start: "Megenagna", passBy: "Bherawi", destination: "Gofa Condo", distance: "12.4 Km" },
  { id: "79", start: "4 Kilo", passBy: "Signal", destination: "Summit", distance: "12.7 Km" },
  { id: "80", start: "Semen Gebeya", passBy: "Kazanchiz", destination: "Megenagna", distance: "12.4 Km" },
  { id: "81", start: "SANSUSI", passBy: "PIYYSA", destination: "MEGENAGNA", distance: "13 Km" },
  { id: "82", start: "Sefera Goro", passBy: "24 kebele", destination: "Balcha Hospital", distance: "14.6 Km" },
  { id: "83", start: "Ayat Condominium", passBy: "kebena", destination: "6 Kilo", distance: "18 Km" },
  { id: "84", start: "Kolfe", passBy: "Amanuel", destination: "Legehar", distance: "9.5 Km" },
  { id: "85", start: "Merkato", passBy: "18 Mazoria", destination: "Holeta", distance: "45 Km" },
  { id: "86", start: "Ayertena", passBy: "Mebrat Hail", destination: "Korki Fabrica", distance: "12.3 Km" },
  { id: "87", start: "Wingate college", passBy: "Ketena 2", destination: "Ayertena", distance: "10.5 Km" },
  { id: "88", start: "ADDIS KETEMA", passBy: "Piazza", destination: "Chancho", distance: "40 Km" },
  { id: "89", start: "ADDIS KETEMA", passBy: "4 Kilo", destination: "Sendafa", distance: "44 Km" },
  { id: "90", start: "Betel Hospital", passBy: "Torhailoch", destination: "Legehar", distance: "10 Km" },
  { id: "91", start: "Merkato", passBy: "Torhailoch", destination: "Teji", distance: "52 Km" },
  { id: "92", start: "Hanamariam", passBy: "Sar bet", destination: "Balcha Hospital", distance: "9.6 Km" },
  { id: "93", start: "Bole Bulbula", passBy: "Bole Airport", destination: "Megenagna", distance: "15.2 Km" },
  { id: "94", start: "Piazza", passBy: "Pawlos", destination: "Mekililand Birchko Fabrica", distance: "9.9 Km" },
  { id: "95", start: "Merkato", passBy: "Fil Doro", destination: "Addisalem", distance: "47 Km" },
  { id: "96", start: "Megenagna", passBy: "Anbessa Gerag", destination: "Goro Sefera", distance: "7 Km" },
  { id: "97", start: "Megenagna", passBy: "Ayat", destination: "Legetafo", distance: "15.8 Km" },
  { id: "98", start: "Dukem", passBy: "Gelan", destination: "Saris Abo", distance: "26.3 Km" },
  { id: "99", start: "Ayertena", passBy: "Welete", destination: "Alemgena", distance: "8.3 Km" },
  { id: "100", start: "Jemo Site", passBy: "Dese Hotel", destination: "Merkato", distance: "14.5 Km" },
  { id: "101", start: "Megenagna", passBy: "Ayat", destination: "Yeka Ayat Con.1sq", distance: "12 Km" },
  { id: "102", start: "Legehar", passBy: "Magenagna", destination: "Karalo", distance: "13.7 Km" },
  { id: "103", start: "Jemo 3", passBy: "Mexico", destination: "Piazza", distance: "12.2 Km" },
  { id: "104", start: "Addisu Gebeya", passBy: "Mexico", destination: "SARIS", distance: "12 Km" },
  { id: "105", start: "Lagehar", passBy: "TORHAYLOCHE", destination: "Anfo meda", distance: "12 Km" },
  { id: "106", start: "MEXICO", passBy: "SARBET", destination: "KOYEFECHE", distance: "10.8 Km" },
  { id: "107", start: "TULUDIMTU", passBy: "MEXICO", destination: "PIYASA", distance: "11.4 Km" },
  { id: "108", start: "Minilik square", passBy: "Winget", destination: "Asco Addisu Sefer", distance: "9.3 Km" },
  { id: "109", start: "Saris Abo", passBy: "Kaliti", destination: "tulu dimtu", distance: "12 Km" },
  { id: "110", start: "Akaki", passBy: "Meskel Square", destination: "6 kilo", distance: "24.9 Km" },
  { id: "111", start: "Piazza", passBy: "Medhanialm school", destination: "Dire Sololiya", distance: "16.6 Km" },
  { id: "112", start: "ADDISUGEBYEA", passBy: "-", destination: "MEGENAGNA", distance: "N/A" },
  { id: "115", start: "MEXICO", passBy: "-", destination: "SEFERA", distance: "N/A" },
  { id: "117", start: "MEXICO", passBy: "-", destination: "HAILEGARMENT", distance: "N/A" },
  { id: "121", start: "MEXICO", passBy: "HAILEGARMENT", destination: "TULUDIMTU", distance: "N/A" },
];
